export const Data = {
  Category: [
    {
      id: '1',
      category: 'Sennheiser',
      icon: require('./Assets/icon1.png'),
      bgcolor: '#E9EDEF',
    },
    {
      id: '2',
      category: 'Sony',
      icon: require('./Assets/icon2.png'),
      bgcolor: '#E9EDEF',
    },
    {
      id: '3',
      category: 'Beats by Dre',
      icon: require('./Assets/icon3.png'),
      bgcolor: '#E9EDEF',
    },
    {
      id: '4',
      category: 'JBL Professional',
      icon: require('./Assets/icon4.png'),
      bgcolor: '#E9EDEF',
    },
    {
      id: '5',
      category: 'Bang & Olufsen',
      icon: require('./Assets/icon5.png'),
      bgcolor: '#E9EDEF',
    },
  ],
  Product: [
    {
      id: '1',
      categoryid: '1',
      product: 'Sennheiser HD 450BT',
      image: require('./Assets/1.png'),
      dis:
        'The HD 450BT delivers captivating sound that you can enjoy without distraction – even in loud environments.',
      bgcolor: '#E9EDEF',
      price: '586',
      added: 0,
    },
    {
      id: '2',
      categoryid: '1',
      product: 'Sennheiser HD 350BT',
      image: require('./Assets/2.png'),
      dis:
        'The HD 350BT delivers an engaging sound experience with deep dynamic bass. Flawless transmission is assured by the latest wireless technology.',
      bgcolor: '#E9EDEF',
      price: '647',
      added: 0,
    },
    {
      id: '3',
      categoryid: '1',
      product: 'Sennheiser PXC 550-II Wireless',
      image: require('./Assets/3.png'),
      dis:
        'Adaptive Noise Cancellation automatically adjusts to your surroundings to suppress unwanted background noise.',
      bgcolor: '#E9EDEF',
      price: '354',
      added: 0,
    },
    {
      id: '4',
      categoryid: '1',
      product: 'Sennheiser MOMENTUM 3 Wireless',
      image: require('./Assets/4.png'),
      dis:
        'Offering superior sound, cutting-edge technology, and a modern design aesthetic to every moment.',
      bgcolor: '#E9EDEF',
      price: '267',
      added: 0,
    },
    {
      id: '5',
      categoryid: '1',
      product: 'Sennheiser MOMENTUM On-Ear Wireless',
      image: require('./Assets/5.png'),
      dis:
        'Combines high-resolution sound with a lightweight, puristic design and exclusive materials like stainless steel and Alcantara®.',
      bgcolor: '#E9EDEF',
      price: '598',
      added: 0,
    },
    {
      id: '6',
      categoryid: '1',
      product: 'Sennheiser MM 450-X TRAVEL',
      image: require('./Assets/6.png'),
      dis:
        'Advanced Sennheiser active noise cancellation lets you enjoy music in peace.',
      bgcolor: '#E9EDEF',
      price: '642',
      added: 0,
    },
    {
      id: '7',
      categoryid: '2',
      product: 'WH-1000XM4 Wireless Noise Cancelling Headphones',
      image: require('./Assets/7.png'),
      dis:
        'Whether you’re flying long-haul or relaxing in a café, the WH-1000XM4 headphones deliver our best ever noise cancelling performance.',
      bgcolor: '#E9EDEF',
      price: '355',
      added: 0,
    },
    {
      id: '8',
      categoryid: '2',
      product: 'WH-XB900N Wireless Noise Cancelling Headphones',
      image: require('./Assets/8.png'),
      dis:
        'As part of the EXTRA BASS™ 1 range from Sony, the WH-XB900N noise cancelling headphones enhance all your low-end frequencies for exceptional bass.',
      bgcolor: '#E9EDEF',
      price: '754',
      added: 0,
    },
    {
      id: '9',
      categoryid: '2',
      product: 'WH-XB700 Bluetooth Wireless Headphones',
      image: require('./Assets/9.png'),
      dis:
        'If your headphones are running low on power, a 10-minute quick charge will give you up to 90 minutes of play time. Ideal if you’re rushing around from place to place.',
      bgcolor: '#E9EDEF',
      price: '394',
      added: 0,
    },
    {
      id: '10',
      categoryid: '2',
      product: 'WH-CH710N Wireless Noise Cancelling Headphone',
      image: require('./Assets/10.png'),
      dis:
        'Dual microphones feeding forwards and backwards mean the WH-CH710N headphones catch more ambient sounds than ever before.',
      bgcolor: '#E9EDEF',
      price: '246',
      added: 0,
    },
    {
      id: '11',
      categoryid: '2',
      product: 'MDR-ZX310 / ZX310AP Headphones',
      image: require('./Assets/11.png'),
      dis:
        'Lightweight, folding design for ultimate music mobility, 30mm ferrite drivers for powerful, balanced sound',
      bgcolor: '#E9EDEF',
      price: '367',
      added: 0,
    },
    {
      id: '12',
      categoryid: '2',
      product: 'ZX110 Headphones',
      image: require('./Assets/12.png'),
      dis:
        'High energy neodymium magnets deliver powerful sound, 12Hz–22kHz frequency range',
      bgcolor: '#E9EDEF',
      price: '359',
      added: 0,
    },
    {
      id: '13',
      categoryid: '3',
      product: 'Beats EP',
      image: require('./Assets/13.png'),
      dis:
        'Powered by fine-tuned acoustics for incredible clarity, breadth, and balance, it’s the ideal introduction to Beats for any music lover.',
      bgcolor: '#E9EDEF',
      price: '845',
      added: 0,
    },
    {
      id: '14',
      categoryid: '3',
      product: 'Beats Solo3 Wireless',
      image: require('./Assets/14.png'),
      dis:
        'On-ear controls with dual beam-forming mics allow you to take calls, play music, adjust volume, and voice activate wherever your day takes you.',
      bgcolor: '#E9EDEF',
      price: '648',
      added: 0,
    },
    {
      id: '15',
      categoryid: '3',
      product: 'Beats Studio3 Wireless',
      image: require('./Assets/15.png'),
      dis:
        'Real-time audio calibration preserves clarity, range, and emotion to deliver a premium listening experience.',
      bgcolor: '#E9EDEF',
      price: '492',
      added: 0,
    },
    {
      id: '16',
      categoryid: '3',
      product: 'Beats Solo Pro',
      image: require('./Assets/16.png'),
      dis:
        'Switch seamlessly between Noise Cancelling with real-time audio calibration, or Transparency Mode to stay aware of your surroundings.',
      bgcolor: '#E9EDEF',
      price: '355',
      added: 0,
    },
    {
      id: '17',
      categoryid: '3',
      product: 'Powerbeats',
      image: require('./Assets/17.png'),
      dis:
        'Adjustable, secure-fit earhooks are customizable with multiple eartip options, and are made to stay in place, no matter how hard you go.',
      bgcolor: '#E9EDEF',
      price: '754',
      added: 0,
    },
    {
      id: '18',
      categoryid: '3',
      product: 'Powerbeats Pro',
      image: require('./Assets/18.png'),
      dis:
        'Auto Play/Pause, independent earbud connection via the Apple H1 chip, and full volume and track controls on each earbud mean you’re in charge of how you listen.',
      bgcolor: '#E9EDEF',
      price: '394',
      added: 0,
    },
    {
      id: '19',
      categoryid: '4',
      product: 'JBL Quantum 100',
      image: require('./Assets/19.png'),
      dis: 'Wired over-ear gaming headset with a detachable mic',
      bgcolor: '#E9EDEF',
      price: '246',
      added: 0,
    },
    {
      id: '20',
      categoryid: '4',
      product: 'JBL TUNE 500BT',
      image: require('./Assets/20.png'),
      dis: 'Wireless on-ear headphones',
      bgcolor: '#E9EDEF',
      price: '647',
      added: 0,
    },
    {
      id: '21',
      categoryid: '4',
      product: 'UA Sport Wireless Train Project Rock',
      image: require('./Assets/21.png'),
      dis: 'On-ear sport Headphones',
      bgcolor: '#E9EDEF',
      price: '354',
      added: 0,
    },
    {
      id: '22',
      categoryid: '4',
      product: 'JBL Quantum 400',
      image: require('./Assets/22.png'),
      dis: 'USB over-ear gaming headset with game-chat dial',
      bgcolor: '#E9EDEF',
      price: '267',
      added: 0,
    },
    {
      id: '23',
      categoryid: '4',
      product: 'JBL LIVE 500BT',
      image: require('./Assets/23.png'),
      dis: 'Wireless Over-Ear Headphones',
      bgcolor: '#E9EDEF',
      price: '598',
      added: 0,
    },
    {
      id: '24',
      categoryid: '4',
      product: 'JBL TUNE 700BT',
      image: require('./Assets/24.png'),
      dis: 'Wireless Over-Ear Headphones',
      bgcolor: '#E9EDEF',
      price: '642',
      added: 0,
    },
    {
      id: '25',
      categoryid: '5',
      product: 'Beoplay H95',
      image: require('./Assets/25.png'),
      dis:
        'Beoplay H95 is crafted for the ultimate listening experience with long lasting comfort and effective Active Noise Cancellation.',
      bgcolor: '#E9EDEF',
      price: '355',
      added: 0,
    },
    {
      id: '26',
      categoryid: '5',
      product: 'Beoplay H9 3rd Gen',
      image: require('./Assets/26.png'),
      dis:
        'Comfortable Active Noise Cancelling over-ear headphones with touch interface and up to 25 hours of playtime.',
      bgcolor: '#E9EDEF',
      price: '754',
      added: 0,
    },
    {
      id: '27',
      categoryid: '5',
      product: 'Beoplay H4 2nd Gen',
      image: require('./Assets/27.png'),
      dis:
        'Contemporary over-ear headphones with long-lasting comfort, superior sound and voice assistant.',
      bgcolor: '#E9EDEF',
      price: '394',
      added: 0,
    },
    {
      id: '28',
      categoryid: '5',
      product: 'Beoplay H8i',
      image: require('./Assets/28.png'),
      dis:
        'Luxurious Active Noise Cancelling on-ear headphones designed for superior style and comfort. Up to 30 hours of wireless Bang & Olufsen Signature Sound.',
      bgcolor: '#E9EDEF',
      price: '246',
      added: 0,
    },
    {
      id: '29',
      categoryid: '5',
      product: 'Beoplay E8 3rd Gen',
      image: require('./Assets/29.png'),
      dis:
        'QI-certified wireless charging case and Bluetooth 5.1 connectivity ensure a seamless and powerful listening experience.',
      bgcolor: '#E9EDEF',
      price: '647',
      added: 0,
    },
    {
      id: '30',
      categoryid: '5',
      product: 'Beoplay E8 Sport',
      image: require('./Assets/30.png'),
      dis:
        'Wireless earphones designed for sport. Expertly crafted for powerful music performance in any weather. Waterproof, secure-fitting, and long-lasting battery life.',
      bgcolor: '#E9EDEF',
      price: '354',
      added: 0,
    },
  ],
};
